jasypt:
  encryptor:
    algorithm: PBEWITHSHA1ANDDESEDE
    keyObtentionIterations: 10000

spring:
  jpa:
    hibernate:
      ddl-auto: none

server:
  ssl:
    enabled: true
    key-store: /home/justin/ssl/spring_cloud_demo.jks
    key-store-password: ENC(C9S/riFqH1Xm8GRSqZws7REooMNN1Tr9RvYY3vHBWf0=)
    key-store-type: JKS
    key-alias: spring_cloud_demo
