spring:
  profiles: eureka1
  security:
    user:
      name: eureka
      password: DCRrdKUwq3293MLMBbFK
server:
  port: 8761
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://eureka:DCRrdKUwq3293MLMBbFK@eureka1:8761/eureka/,http://eureka:DCRrdKUwq3293MLMBbFK@eureka2:8762/eureka/
  instance:
    hostname: eureka1
    appname: SERVICE-REGISTRY-CLUSTER

---
spring:
  profiles: eureka2
  security:
    user:
      name: eureka
      password: DCRrdKUwq3293MLMBbFK
server:
  port: 8762
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://eureka:DCRrdKUwq3293MLMBbFK@eureka1:8761/eureka/,http://eureka:DCRrdKUwq3293MLMBbFK@eureka2:8762/eureka/
  instance:
    hostname: eureka2
    appname: SERVICE-REGISTRY-CLUSTER