server:
  ssl:
    enabled: true
    key-store: /home/justin/ssl/spring_cloud_demo.jks
    key-store-password: ENC(C9S/riFqH1Xm8GRSqZws7REooMNN1Tr9RvYY3vHBWf0=)
    key-store-type: JKS
    key-alias: spring_cloud_demo
  shutdown: graceful

spring:
  application:
    name: eureka-server
  security:
    user:
      name: eureka
      password: ${eureka_password}
  lifecycle:
    timeout-per-shutdown-phase: 30s

eureka:
  instance:
    secure-port-enabled: true
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: https://eureka:${eureka_password}@eureka1:8761/eureka/,https://eureka:${eureka_password}@eureka2:8762/eureka/

management:
  endpoints:
    web:
      exposure:
        include: info,health,prometheus

ssl:
  bypass-host-verification: true
---
spring:
  profiles: eureka1
server:
  port: 8761
eureka:
  instance:
    hostname: eureka1

---
spring:
  profiles: eureka2
server:
  port: 8762
eureka:
  instance:
    hostname: eureka2
