jasypt:
  encryptor:
    algorithm: PBEWITHSHA1ANDDESEDE
    keyObtentionIterations: 10000

---
spring:
  profiles: eureka1
  security:
    user:
      name: ${eureka_username}
      password: ${eureka_password}
server:
  port: 8761
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://${eureka_username}:${eureka_password}@eureka1:8761/eureka/,http://${eureka_username}:${eureka_password}@eureka2:8762/eureka/
  instance:
    hostname: eureka1
    appname: SERVICE-REGISTRY-CLUSTER

---
spring:
  profiles: eureka2
  security:
    user:
      name: ${eureka_username}
      password: ${eureka_password}
server:
  port: 8762
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://${eureka_username}:${eureka_password}@eureka1:8761/eureka/,http://${eureka_username}:${eureka_password}@eureka2:8762/eureka/
  instance:
    hostname: eureka2
    appname: SERVICE-REGISTRY-CLUSTER