jasypt:
  encryptor:
    algorithm: PBEWITHSHA1ANDDESEDE
    keyObtentionIterations: 10000

server:
  ssl:
    enabled: true
    key-store: /home/justin/ssl/spring_cloud_demo.jks
    key-store-password: ENC(C9S/riFqH1Xm8GRSqZws7REooMNN1Tr9RvYY3vHBWf0=)
    key-store-type: JKS
    key-alias: spring_cloud_demo

spring:
  security:
    user:
      name: eureka
      password: ${eureka_password}

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: https://eureka:${eureka_password}@myhost:8761/eureka/
  instance:
    appname: SERVICE-REGISTRY-CLUSTER

---
spring:
  profiles: eureka1
server:
  port: 8761
eureka:
  instance:
    hostname: eureka1

---
spring:
  profiles: eureka2
server:
  port: 8762
eureka:
  instance:
    hostname: eureka2
