server:
    port: 9000

spring:
    cloud:
        config:
            server:
                git:
                    uri: https://github.com/justinpmliu/spring-cloud.git
                    search-paths:
                    - config
