server:
  port: 9000

spring:
  security:
    user:
      name: conf
      password: DCRrdKUwq3293MLMBbFK
  cloud:
    config:
      server:
        git:
          uri: git@github.com:justinpmliu/spring-cloud.git
          search-paths:
            - config
