jasypt:
  encryptor:
    algorithm: PBEWITHSHA1ANDDESEDE
    keyObtentionIterations: 10000

server:
  port: 9000

spring:
    security:
        user:
            name: conf
            password: ENC(5FnO1fhjCAGneCBVYLaBXEamFJgqKrWD)
    cloud:
        config:
            server:
                git:
                    uri: https://github.com/justinpmliu/config-repo.git

