jasypt:
  encryptor:
    algorithm: PBEWITHSHA1ANDDESEDE
    keyObtentionIterations: 10000

server:
  port: 9000
  ssl:
    enabled: true
    key-store: /home/justin/ssl/spring_cloud_demo.jks
    key-store-password: ENC(C9S/riFqH1Xm8GRSqZws7REooMNN1Tr9RvYY3vHBWf0=)
    key-store-type: JKS
    key-alias: spring_cloud_demo

spring:
  application:
    name: config-server
  security:
    user:
      name: conf
      password: ENC(5FnO1fhjCAGneCBVYLaBXEamFJgqKrWD)
  cloud:
    config:
      server:
        git:
          uri: /home/justin/git/config-repo

eureka:
  instance:
    secure-port-enabled: true
  client:
    service-url:
      defaultZone: https://eureka:${eureka_password}@eureka1:8761/eureka/, https://eureka:${eureka_password}@eureka2:8762/eureka/

management:
  endpoints:
    web:
      exposure:
        include: info,health,prometheus
